### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by mfriedrich7** [pdepjm/2024-tp0-presentacion-Valentin-Sosa#1]
Seguís entrenando/compitiendo al día de hoy? yo soy el que estaba al lado tuyo ajjaja, también hice kick y muay thai pero dejé hace como 4 años (tuve 1 exhibición nomas)

**Comment by Valentin-Sosa** [comment]
Si sigo entrenando, competir esta medio jodido con la cantidad de tiempo que te consume la facultad pero entreno para competir este año.
